/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MapImport } from './routes/map'
import { Route as GeojsonImport } from './routes/geojson'
import { Route as GeocoderImport } from './routes/geocoder'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MapRoute = MapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRoute,
} as any)

const GeojsonRoute = GeojsonImport.update({
  id: '/geojson',
  path: '/geojson',
  getParentRoute: () => rootRoute,
} as any)

const GeocoderRoute = GeocoderImport.update({
  id: '/geocoder',
  path: '/geocoder',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/geocoder': {
      id: '/geocoder'
      path: '/geocoder'
      fullPath: '/geocoder'
      preLoaderRoute: typeof GeocoderImport
      parentRoute: typeof rootRoute
    }
    '/geojson': {
      id: '/geojson'
      path: '/geojson'
      fullPath: '/geojson'
      preLoaderRoute: typeof GeojsonImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/geocoder': typeof GeocoderRoute
  '/geojson': typeof GeojsonRoute
  '/map': typeof MapRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/geocoder': typeof GeocoderRoute
  '/geojson': typeof GeojsonRoute
  '/map': typeof MapRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/geocoder': typeof GeocoderRoute
  '/geojson': typeof GeojsonRoute
  '/map': typeof MapRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/geocoder' | '/geojson' | '/map'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/geocoder' | '/geojson' | '/map'
  id: '__root__' | '/' | '/about' | '/geocoder' | '/geojson' | '/map'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GeocoderRoute: typeof GeocoderRoute
  GeojsonRoute: typeof GeojsonRoute
  MapRoute: typeof MapRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GeocoderRoute: GeocoderRoute,
  GeojsonRoute: GeojsonRoute,
  MapRoute: MapRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/geocoder",
        "/geojson",
        "/map"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/geocoder": {
      "filePath": "geocoder.tsx"
    },
    "/geojson": {
      "filePath": "geojson.tsx"
    },
    "/map": {
      "filePath": "map.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
